language: python
sudo: true
cache: pip
addons:
  apt:
    packages:
      - gdb
env:
  global:
    - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
    - SEGFAULT_SIGNALS=all
    - SETUPPY_CFLAGS=-DCYTHON_TRACE=1
    - PYTEST_ADDOPTS=--benchmark-disable
  matrix:
    - TOXENV=check
    - TOXENV=docs
matrix:
  include:
    - python: '2.7'
      env:
        - TOXENV=py27-pure-cover,report,coveralls,codecov
    - python: '2.7'
      env:
        - TOXENV=py27-pure-nocov
    - os: osx
      language: generic
      env:
        - TOXENV=py27-pure-nocov
        - SETUPPY_CFLAGS=
        - CIBW_BUILD=cp27-*
      script:
    - python: '2.7'
      env:
        - TOXENV=py27-cython-cover,report,coveralls,codecov
        - CIBW_BUILD=cp27-manylinux1_x86_64

    - python: '2.7'
      env:
        - TOXENV=py27-cython-nocov
        - CIBW_BUILD=cp27-manylinux1_x86_64

    - os: osx
      language: generic
      env:
        - TOXENV=py27-cython-nocov
        - SETUPPY_CFLAGS=
        - CIBW_BUILD=cp27-*
      script:
    - python: '3.4'
      env:
        - TOXENV=py34-pure-cover,report,coveralls,codecov
    - python: '3.4'
      env:
        - TOXENV=py34-pure-nocov
    - os: osx
      language: generic
      env:
        - TOXENV=py34-pure-nocov
        - SETUPPY_CFLAGS=
        - CIBW_BUILD=cp34-*
      script:
    - python: '3.4'
      env:
        - TOXENV=py34-cython-cover,report,coveralls,codecov
        - CIBW_BUILD=cp34-manylinux1_x86_64

    - python: '3.4'
      env:
        - TOXENV=py34-cython-nocov
        - CIBW_BUILD=cp34-manylinux1_x86_64

    - os: osx
      language: generic
      env:
        - TOXENV=py34-cython-nocov
        - SETUPPY_CFLAGS=
        - CIBW_BUILD=cp34-*
      script:
    - python: '3.5'
      env:
        - TOXENV=py35-pure-cover,report,coveralls,codecov
    - python: '3.5'
      env:
        - TOXENV=py35-pure-nocov
    - os: osx
      language: generic
      env:
        - TOXENV=py35-pure-nocov
        - SETUPPY_CFLAGS=
        - CIBW_BUILD=cp35-*
      script:
    - python: '3.5'
      env:
        - TOXENV=py35-cython-cover,report,coveralls,codecov
        - CIBW_BUILD=cp35-manylinux1_x86_64

    - python: '3.5'
      env:
        - TOXENV=py35-cython-nocov
        - CIBW_BUILD=cp35-manylinux1_x86_64

    - os: osx
      language: generic
      env:
        - TOXENV=py35-cython-nocov
        - SETUPPY_CFLAGS=
        - CIBW_BUILD=cp35-*
      script:
    - python: '3.6'
      env:
        - TOXENV=py36-pure-cover,report,coveralls,codecov
    - python: '3.6'
      env:
        - TOXENV=py36-pure-nocov
    - os: osx
      language: generic
      env:
        - TOXENV=py36-pure-nocov
        - SETUPPY_CFLAGS=
        - CIBW_BUILD=cp36-*
      script:
    - python: '3.6'
      env:
        - TOXENV=py36-cython-cover,report,coveralls,codecov
        - CIBW_BUILD=cp36-manylinux1_x86_64

    - python: '3.6'
      env:
        - TOXENV=py36-cython-nocov
        - CIBW_BUILD=cp36-manylinux1_x86_64

    - os: osx
      language: generic
      env:
        - TOXENV=py36-cython-nocov
        - SETUPPY_CFLAGS=
        - CIBW_BUILD=cp36-*
      script:
    - python: '3.7'
      env:
        - TOXENV=py37-pure-cover,report,coveralls,codecov      sudo: required
      dist: xenial

    - python: '3.7'
      env:
        - TOXENV=py37-pure-nocov      sudo: required
      dist: xenial

    - os: osx
      language: generic
      env:
        - TOXENV=py37-pure-nocov
        - SETUPPY_CFLAGS=
        - CIBW_BUILD=cp37-*
      script:
    - python: '3.7'
      env:
        - TOXENV=py37-cython-cover,report,coveralls,codecov
        - CIBW_BUILD=cp37-manylinux1_x86_64
      sudo: required
      dist: xenial

    - python: '3.7'
      env:
        - TOXENV=py37-cython-nocov
        - CIBW_BUILD=cp37-manylinux1_x86_64
      sudo: required
      dist: xenial

    - os: osx
      language: generic
      env:
        - TOXENV=py37-cython-nocov
        - SETUPPY_CFLAGS=
        - CIBW_BUILD=cp37-*
      script:
    - python: 'pypy'
      env:
        - TOXENV=pypy-pure-cover,report,coveralls,codecov
    - python: 'pypy'
      env:
        - TOXENV=pypy-pure-nocov
    - python: 'pypy'
      env:
        - TOXENV=pypy-cython-cover,report,coveralls,codecov
    - python: 'pypy'
      env:
        - TOXENV=pypy-cython-nocov
    - python: 'pypy3'
      env:
        - TOXENV=pypy3-pure-cover,report,coveralls,codecov
    - python: 'pypy3'
      env:
        - TOXENV=pypy3-pure-nocov
    - python: 'pypy3'
      env:
        - TOXENV=pypy3-cython-cover,report,coveralls,codecov
    - python: 'pypy3'
      env:
        - TOXENV=pypy3-cython-nocov
before_install:
  - python --version
  - uname -a
  - lsb_release -a || true
  - sudo sysctl -w kernel.yama.ptrace_scope=0 || true
install:
  - pip install cibuildwheel twine tox-wheel
  - virtualenv --version
  - easy_install --version
  - pip --version
  - tox --version
  - |
    set -ex
    if [[ $TRAVIS_PYTHON_VERSION == "pypy" ]]; then
      (cd $HOME
       wget https://bitbucket.org/pypy/pypy/downloads/pypy2-v6.0.0-linux64.tar.bz2
       tar xf pypy2-*.tar.bz2
       pypy2-*/bin/pypy -m ensurepip
       pypy2-*/bin/pypy -m pip install -U virtualenv)
      export PATH=$(echo $HOME/pypy2-*/bin):$PATH
      export TOXPYTHON=$(echo $HOME/pypy2-*/bin/pypy)
    fi
    if [[ $TRAVIS_PYTHON_VERSION == "pypy3" ]]; then
      (cd $HOME
       wget https://bitbucket.org/pypy/pypy/downloads/pypy3-v6.0.0-linux64.tar.bz2
       tar xf pypy3-*.tar.bz2
       pypy3-*/bin/pypy3 -m ensurepip
       pypy3-*/bin/pypy3 -m pip install -U virtualenv)
      export PATH=$(echo $HOME/pypy3-*/bin):$PATH
      export TOXPYTHON=$(echo $HOME/pypy3-*/bin/pypy3)
    fi
    set +x
script:
  - |
    set -ex
    if [[ -n "$CIBW_BUILD" ]]; then
      cibuildwheel --output-dir=dist
      for wheel in dist/*.whl; do
        tox --installpkg=$wheel -v
      done
      if [[ TOXENV =~ cython ]]; then
        twine upload --repository-url https://test.pypi.org/legacy/ --skip-existing dist/*
      fi
    else:
      tox -v
    fi
after_failure:
  - more .tox/log/* | cat
  - more .tox/*/log/* | cat
notifications:
  email:
    on_success: never
    on_failure: always
