language: python
sudo: true
cache: pip
addons:
  apt:
    packages:
      - gdb
env:
  global:
    - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
    - SEGFAULT_SIGNALS=all
    - SETUPPY_CFLAGS=-DCYTHON_TRACE=1
    - PYTEST_ADDOPTS=--benchmark-disable
  matrix:
    - TOXENV=check
    - TOXENV=docs
matrix:
  include:
{% for env in tox_environments %}
    - python: '{{ env.split("-")[0] if env.startswith("pypy") else "{0[2]}.{0[3]}".format(env) }}'
      env:
        - TOXENV={{ env }}{% if "cover" in env %},report,coveralls,codecov{% endif %}
{% if "pure" not in env and "pypy" not in env %}{{ '' }}
        - CIBW_BUILD=cp{{ env.split("-")[0][2:] }}-manylinux1_x86_64
{% endif %}
{% if "py37" in env %}
      sudo: required
      dist: xenial
{% endif %}

{% if "pypy" not in env and "cover" not in env %}
    - os: osx
      language: generic
      env:
        - TOXENV={{ env }}
        - SETUPPY_CFLAGS=
        - CIBW_BUILD=cp{{ env.split("-")[0][2:] }}-*
      script:
{% endif %}
{% endfor %}
before_install:
  - python --version
  - uname -a
  - lsb_release -a || true
  - sudo sysctl -w kernel.yama.ptrace_scope=0 || true
install:
  - pip install cibuildwheel twine tox-wheel
  - virtualenv --version
  - easy_install --version
  - pip --version
  - tox --version
  - |
    set -ex
    if [[ $TRAVIS_PYTHON_VERSION == "pypy" ]]; then
      (cd $HOME
       wget https://bitbucket.org/pypy/pypy/downloads/pypy2-v6.0.0-linux64.tar.bz2
       tar xf pypy2-*.tar.bz2
       pypy2-*/bin/pypy -m ensurepip
       pypy2-*/bin/pypy -m pip install -U virtualenv)
      export PATH=$(echo $HOME/pypy2-*/bin):$PATH
      export TOXPYTHON=$(echo $HOME/pypy2-*/bin/pypy)
    fi
    if [[ $TRAVIS_PYTHON_VERSION == "pypy3" ]]; then
      (cd $HOME
       wget https://bitbucket.org/pypy/pypy/downloads/pypy3-v6.0.0-linux64.tar.bz2
       tar xf pypy3-*.tar.bz2
       pypy3-*/bin/pypy3 -m ensurepip
       pypy3-*/bin/pypy3 -m pip install -U virtualenv)
      export PATH=$(echo $HOME/pypy3-*/bin):$PATH
      export TOXPYTHON=$(echo $HOME/pypy3-*/bin/pypy3)
    fi
    set +x
script:
  - |
    set -ex
    if [[ -n "$CIBW_BUILD" ]]; then
      cibuildwheel --output-dir=dist
      for wheel in dist/*.whl; do
        tox --installpkg=$wheel -v
      done
      if [[ TOXENV =~ cython ]]; then
        twine upload --repository-url https://test.pypi.org/legacy/ --skip-existing dist/*
      fi
    else:
      tox -v
    fi
after_failure:
  - more .tox/log/* | cat
  - more .tox/*/log/* | cat
notifications:
  email:
    on_success: never
    on_failure: always
